### ISSUE TITLE
 Failed to login to game server! Error code: 1B - Warmane WOTLK 3.3.5

### ISSUE THREAD

**Issue by dusancvetanovic** [fjaros/wowchat#75]
Hello fjaros and thank you for creating this tool.
My friend recommended me this project and I wanted to see how it works.
I did everything right and after running the jar it says: Invalid game version for this server!

`07:19:41.807 [main] INFO wowchat.WoWChat$ - Running WoWChat - v1.3.8
07:19:42.639 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory -                                                                                                                                                              Using SLF4J as the default logging framework
07:19:42.650 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty                                                                                                                                                             .noUnsafe: false
07:19:42.651 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java versi                                                                                                                                                             on: 8
07:19:42.652 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.U                                                                                                                                                             nsafe.theUnsafe: available
07:19:42.653 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.U                                                                                                                                                             nsafe.copyMemory: available
07:19:42.654 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.B                                                                                                                                                             uffer.address: available
07:19:42.658 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buf                                                                                                                                                             fer constructor: available
07:19:42.659 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.B                                                                                                                                                             its.unaligned: available, true
07:19:42.659 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.intern                                                                                                                                                             al.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
07:19:42.659 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.D                                                                                                                                                             irectByteBuffer.<init>(long, int): available
07:19:42.659 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Un                                                                                                                                                             safe: available
07:19:42.660 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.                                                                                                                                                             tmpdir: /tmp (java.io.tmpdir)
07:19:42.660 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.                                                                                                                                                             bitMode: 64 (sun.arch.data.model)
07:19:42.663 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.                                                                                                                                                             maxDirectMemory: 251396096 bytes
07:19:42.663 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.                                                                                                                                                             uninitializedArrayAllocationThreshold: -1
07:19:42.664 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuf                                                                                                                                                             fer.cleaner(): available
07:19:42.665 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.                                                                                                                                                             noPreferDirect: false
07:19:47.183 [main] INFO wowchat.WoWChat$ - Connecting to Discord...
07:19:47.815 [JDA RateLimit-Worker 1] DEBUG net.dv8tion.jda.internal.requests.Re                                                                                                                                                             quester - Received response with following cf-rays: [70461073ed937c70-BEG]
07:19:48.423 [JDA RateLimit-Worker 2] DEBUG net.dv8tion.jda.internal.requests.Re                                                                                                                                                             quester - Received response with following cf-rays: [704610768e227c70-BEG]
07:19:48.432 [main] INFO net.dv8tion.jda.api.JDA - Login Successful!
07:19:48.487 [main] DEBUG net.dv8tion.jda.api.utils.SessionControllerAdapter - C                                                                                                                                                             reating new worker handle for shard pool 0
07:19:48.487 [main] DEBUG net.dv8tion.jda.api.utils.SessionControllerAdapter - R                                                                                                                                                             unning worker
07:19:48.497 [ConcurrentSessionController-Worker-0] DEBUG net.dv8tion.jda.api.ut                                                                                                                                                             ils.SessionControllerAdapter - Running connect node for shard Shard [0 / 1]
07:19:48.834 [JDA MainWS-ReadThread] INFO net.dv8tion.jda.internal.requests.WebS                                                                                                                                                             ocketClient - Connected to WebSocket
07:19:48.834 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.requests.Web                                                                                                                                                             SocketClient - Connected with gateway intents: 1100001011
07:19:48.834 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.requests.Web                                                                                                                                                             SocketClient - Sending Identify-packet...
07:19:48.907 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.requests.Web                                                                                                                                                             SocketClient - Got HELLO packet (OP 10). Initializing keep-alive.
07:19:49.073 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.handle.Guild                                                                                                                                                             SetupController - Setting incomplete count to 1
07:19:49.073 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.handle.Guild                                                                                                                                                             SetupController - Starting 75 second timeout for 1 guilds
07:19:49.256 [JDA MainWS-ReadThread] INFO net.dv8tion.jda.api.JDA - Finished Loa                                                                                                                                                             ding!
07:19:49.348 [JDA MainWS-ReadThread] DEBUG io.netty.channel.MultithreadEventLoop                                                                                                                                                             Group - -Dio.netty.eventLoopThreads: 2
07:19:49.370 [JDA MainWS-ReadThread] DEBUG io.netty.util.internal.InternalThread                                                                                                                                                             LocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
07:19:49.371 [JDA MainWS-ReadThread] DEBUG io.netty.util.internal.InternalThread                                                                                                                                                             LocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
07:19:49.385 [JDA MainWS-ReadThread] DEBUG io.netty.channel.nio.NioEventLoop - -                                                                                                                                                             Dio.netty.noKeySetOptimization: false
07:19:49.385 [JDA MainWS-ReadThread] DEBUG io.netty.channel.nio.NioEventLoop - -                                                                                                                                                             Dio.netty.selectorAutoRebuildThreshold: 512
07:19:49.396 [JDA MainWS-ReadThread] DEBUG io.netty.util.internal.PlatformDepend                                                                                                                                                             ent - org.jctools-core.MpscChunkedArrayQueue: available
07:19:49.406 [JDA MainWS-ReadThread] INFO wowchat.realm.RealmConnector - Connect                                                                                                                                                             ing to realm server logon.warmane.com:3724
07:19:49.495 [JDA MainWS-ReadThread] DEBUG io.netty.channel.DefaultChannelId - -                                                                                                                                                             Dio.netty.processId: 24858 (auto-detected)
07:19:49.509 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtil - -Djava.net.pr                                                                                                                                                             eferIPv4Stack: false
07:19:49.510 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtil - -Djava.net.pr                                                                                                                                                             eferIPv6Addresses: false
07:19:49.514 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtilInitializations                                                                                                                                                              - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
07:19:49.515 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtil - /proc/sys/net                                                                                                                                                             /core/somaxconn: 128
07:19:49.516 [JDA MainWS-ReadThread] DEBUG io.netty.channel.DefaultChannelId - -                                                                                                                                                             Dio.netty.machineId: 00:16:3e:ff:fe:06:52:b0 (auto-detected)
07:19:49.568 [JDA MainWS-ReadThread] DEBUG io.netty.util.ResourceLeakDetector -                                                                                                                                                              -Dio.netty.leakDetection.level: simple
07:19:49.568 [JDA MainWS-ReadThread] DEBUG io.netty.util.ResourceLeakDetector -                                                                                                                                                              -Dio.netty.leakDetection.targetRecords: 4
07:19:49.634 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.numHeapArenas: 2
07:19:49.634 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.numDirectArenas: 2
07:19:49.634 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.pageSize: 8192
07:19:49.634 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.maxOrder: 11
07:19:49.634 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.chunkSize: 16777216
07:19:49.634 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.smallCacheSize: 256
07:19:49.634 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.normalCacheSize: 64
07:19:49.635 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
07:19:49.635 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.cacheTrimInterval: 8192
07:19:49.635 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
07:19:49.635 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.useCacheForAllThreads: true
07:19:49.635 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocato                                                                                                                                                             r - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
07:19:49.716 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.ByteBufUtil - -Dio.ne                                                                                                                                                             tty.allocator.type: pooled
07:19:49.716 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.ByteBufUtil - -Dio.ne                                                                                                                                                             tty.threadLocalDirectBufferSize: 0
07:19:49.716 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.ByteBufUtil - -Dio.ne                                                                                                                                                             tty.maxThreadLocalCharBufferSize: 16384
07:19:49.766 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.handle.Guild                                                                                                                                                             SetupController - Finished setup for guild 966078485846167562 firing cached even                                                                                                                                                             ts 0
07:20:17.549 [JDA RateLimit-Worker 1] DEBUG net.dv8tion.jda.internal.requests.RateLimiter - Removed 2 expired buckets
07:20:25.547 [nioEventLoopGroup-2-1] INFO wowchat.realm.RealmPacketHandlerTBC - Connected! Sending account login information...
07:20:25.566 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
07:20:25.566 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
07:20:25.566 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
07:20:25.566 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
07:20:25.578 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
07:20:25.578 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
07:20:25.580 [nioEventLoopGroup-2-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@2192631a
07:20:25.602 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0000 - 08 27 00 57 6F 57 00 03 03 05 34 30 36 38 78 00 58 53 4F 00 53 55 6E 65 00 00 00 00 7F 00 00 01 09 52 45 4E 44 50 4F 57 45 52
07:20:25.704 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0000 - 00 00 56 1D 86 78 F8 09 FF D6 A1 D9 AC 83 E6 A7 E3 8E FC 02 30 A3 E1 1D 7A CC 46 02 9E FC A1 BD A1 38 01 07 20 B7 9B 3E 2A 87 82 3C AB 8F 5E BF BF 8E B1 01 08 53 50 06 29 8B 5B AD BD 5B 53 E1 89 5E 64 4B 89 43 BF 2E B5 07 AB 4A 57 E0 D4 AE 07 7D 6E 8E C8 FC 46 0E 58 7C 4D C6 E9 60 E5 9E BB B5 CE E1 A3 BA A3 1E 99 A0 0B 21 57 FC 37 3F B3 69 CD D2 F1 00
07:20:25.742 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0001 - 0C E4 0E F4 85 7E CF F0 D4 AF F1 4A F3 98 68 DD BA 28 72 73 8A 9D E7 FC EF D8 8A A0 FC 6A 2E 7C 5E 97 26 13 0A 5B 1D FA 21 37 A4 49 BC 56 FE 01 F4 F3 71 2C 7C 13 21 A3 5A F8 FD A4 0D FF 88 91 D4 2A D8 4A 2B 02 E5 C5 00 00
07:20:25.778 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0001 - 09
07:20:25.778 [nioEventLoopGroup-2-1] ERROR wowchat.realm.RealmPacketHandlerTBC - Invalid game version for this server!`

**Comment by dusancvetanovic** [comment]
Setting client to Windows got it to write something in the discord channel but something is bothering him.

15:26:46.673 [nioEventLoopGroup-4-1] INFO wowchat.realm.RealmPacketHandlerTBC -                                                                                                                                                              Successfully logged into realm server. Looking for realm Frostmourne
15:26:46.673 [nioEventLoopGroup-4-1] DEBUG wowchat.realm.RealmPacketEncoder - SE                                                                                                                                                             ND REALM PACKET: 0010 - 00 00 00 00
15:26:46.723 [nioEventLoopGroup-4-1] DEBUG wowchat.realm.RealmPacketDecoder - RE                                                                                                                                                             CV REALM PACKET: 0010 - 00 00 00 00 04 00 01 00 00 42 6C 61 63 6B 72 6F 63 6B 20                                                                                                                                                              5B 50 76 50 20 6F 6E 6C 79 5D 00 35 31 2E 31 37 38 2E 36 34 2E 39 37 3A 38 30 3                                                                                                                                                             9 35 00 00 00 00 00 00 08 0A 00 00 20 46 72 6F 73 74 6D 6F 75 72 6E 65 00 35 31                                                                                                                                                              2E 31 37 38 2E 36 34 2E 38 37 3A 38 30 39 36 00 00 00 40 40 01 08 0D 01 00 00 49                                                                                                                                                              63 65 63 72 6F 77 6E 00 35 31 2E 39 31 2E 31 30 36 2E 31 34 38 3A 38 30 39 32 0                                                                                                                                                             0 00 00 40 40 00 08 07 01 00 00 4C 6F 72 64 61 65 72 6F 6E 00 35 31 2E 31 37 38                                                                                                                                                              2E 36 34 2E 39 37 3A 38 30 39 31 00 00 00 00 40 00 08 06 10 00
15:26:46.726 [nioEventLoopGroup-4-1] INFO wowchat.game.GameConnector - Connectin                                                                                                                                                             g to game server Frostmourne (51.178.64.87:8096)
15:26:46.770 [nioEventLoopGroup-4-2] INFO wowchat.game.GamePacketHandlerWotLK -                                                                                                                                                              Connected! Authenticating...
15:26:46.808 [nioEventLoopGroup-4-2] DEBUG wowchat.game.GamePacketDecoderWotLK -                                                                                                                                                              RECV PACKET: 01EC - 01 00 00 00 DA 75 4E D3 65 F2 D2 01 D4 87 43 C3 5F 7F 0B EA                                                                                                                                                              80 17 1D A6 5D 03 7E 78 18 24 8A 45 F3 5F CF 16 90 28 0F CD
15:26:46.810 [nioEventLoopGroup-4-2] DEBUG wowchat.game.GamePacketEncoder - SEND                                                                                                                                                              PACKET: 01ED - 00 00 34 30 00 00 00 00 00 00 52 45 4E 44 50 4F 57 45 52 00 00 0                                                                                                                                                             0 00 00 C8 B3 E9 38 00 00 00 00 00 00 00 00 0D 00 00 00 03 00 00 00 00 00 00 00                                                                                                                                                              62 37 82 70 88 09 E5 22 54 E3 AA DE 57 AF 4C 93 40 AB 01 0B 9E 02 00 00 78 9C 75                                                                                                                                                              D2 C1 6A C3 30 0C C6 71 EF 29 76 E9 9B EC B4 B4 50 C2 EA CB E2 9E 8B 62 7F 4B 4                                                                                                                                                             4 6C 39 38 4E B7 F6 3D FA BE 65 B7 0D 94 F3 4F 48 F0 47 AF C6 98 26 F2 FD 4E 25                                                                                                                                                              5C DE FD C8 B8 22 41 EA B9 35 2F E9 7B 77 32 FF BC 40 48 97 D5 57 CE A2 5A 43 A5                                                                                                                                                              47 59 C6 3C 6F 70 AD 11 5F 8C 18 2C 0B 27 9A B5 21 96 C0 32 A8 0B F6 14 21 81 8                                                                                                                                                             A 46 39 F5 54 4F 79 D8 34 87 9F AA E0 01 FD 3A B8 9C E3 A2 E0 D1 EE 47 D2 0B 1D                                                                                                                                                              6D B7 96 2B 6E 3A C6 DB 3C EA B2 72 0C 0D C9 A4 6A 2B CB 0C AF 1F 6C 2B 52 97 FD                                                                                                                                                              84 BA 95 C7 92 2F 59 95 4F E2 A0 82 FB 2D AA DF 73 9C 60 49 68 80 D6 DB E5 09 F                                                                                                                                                             A 13 B8 42 01 DD C4 31 6E 31 0B CA 5F 7B 7B 1C 3E 9E E1 93 C8 8D
15:26:46.898 [nioEventLoopGroup-4-2] DEBUG wowchat.game.GamePacketDecoderWotLK -                                                                                                                                                              RECV PACKET: 01EE - 1B 00 00 00 00 00 00 00 00 00 02 D8 00 00 00 00
15:26:46.898 [nioEventLoopGroup-4-2] ERROR wowchat.game.GamePacketHandlerWotLK -                                                                                                                                                              Failed to login to game server! Error code: 1B
15:26:46.899 [nioEventLoopGroup-4-2] DEBUG wowchat.game.GamePacketDecoderWotLK -                                                                                                                                                              RECV PACKET: 01EE - 1B D7 00 00 00 00
15:26:46.899 [nioEventLoopGroup-4-2] ERROR wowchat.game.GamePacketHandlerWotLK -                                                                                                                                                              Failed to login to game server! Error code: 1B
15:26:46.899 [nioEventLoopGroup-4-2] DEBUG wowchat.common.ReconnectDelay - GET R                                                                                                                                                             ECONNECT DELAY 10
15:26:46.899 [nioEventLoopGroup-4-2] INFO wowchat.WoWChat$ - Disconnected from s                                                                                                                                                             erver! Reconnecting in 10 seconds...
15:26:46.903 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.internal.requests.WebS                                                                                                                                                             ocketClient - Sending normal message {"op":3,"d":{"activities":[{"name":"Connect                                                                                                                                                             ing...","type":0}],"afk":false,"since":1651411606899,"status":"online"}}
15:26:48.805 [nioEventLoopGroup-4-1] DEBUG io.netty.buffer.PoolThreadCache - Fre                                                                                                                                                             ed 15 thread-local buffer(s) from thread: nioEventLoopGroup-4-1
15:26:48.908 [nioEventLoopGroup-4-2] DEBUG io.netty.buffer.PoolThreadCache - Fre                                                                                                                                                             ed 10 thread-local buffer(s) from thread: nioEventLoopGroup-4-2
15:26:56.900 [pool-1-thread-1] INFO wowchat.realm.RealmConnector - Connecting to                                                                                                                                                              realm server logon.warmane.com:3724

**Comment by fjaros** [comment]
ah yeah. Error 1B means there is a login queue in effect. Unfortunately I never wrote support in the bot for it :(

**Comment by fjaros** [comment]
Fixed by https://github.com/fjaros/wowchat/commit/7ffc62e0fd343d570549b2f375b174778c23f541 . Please redownload the release.

**Comment by fjaros** [comment]
> Setting client to Windows got it to write server system messages in the discord channel but something else is bothering him.

Always use platform=Mac whenever possible. It's likely your account will disconnect or be banned due to failing to respond to Warden requests if using Windows.

**Comment by dusancvetanovic** [comment]
Thank you for your swift response. I did a clean mvn build and now I can confirm the queue works on platform=Windows but it gets disconnected after 20 sec or so.
I first tried using platfrom=Mac but then it fails to select the proper version.

`02:01:25.090 [main] INFO wowchat.WoWChat$ - Running WoWChat - v1.3.8
02:01:25.963 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
02:01:25.969 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
02:01:25.970 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
02:01:25.972 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
02:01:25.972 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
02:01:25.973 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
02:01:25.973 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
02:01:25.975 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
02:01:25.982 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
02:01:25.982 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
02:01:25.982 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
02:01:25.983 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
02:01:25.983 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
02:01:25.987 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 251396096 bytes
02:01:25.987 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
02:01:25.988 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
02:01:25.988 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
02:01:30.365 [main] INFO wowchat.WoWChat$ - Connecting to Discord...
02:01:31.027 [JDA RateLimit-Worker 1] DEBUG net.dv8tion.jda.internal.requests.Requester - Received response with following cf-rays: [704c7b9db9927c9a-BEG]
02:01:31.748 [JDA RateLimit-Worker 2] DEBUG net.dv8tion.jda.internal.requests.Requester - Received response with following cf-rays: [704c7ba13ab77c9a-BEG]
02:01:31.758 [main] INFO net.dv8tion.jda.api.JDA - Login Successful!
02:01:31.844 [main] DEBUG net.dv8tion.jda.api.utils.SessionControllerAdapter - Creating new worker handle for shard pool 0
02:01:31.845 [main] DEBUG net.dv8tion.jda.api.utils.SessionControllerAdapter - Running worker
02:01:31.864 [ConcurrentSessionController-Worker-0] DEBUG net.dv8tion.jda.api.utils.SessionControllerAdapter - Running connect node for shard Shard [0 / 1]
02:01:32.281 [JDA MainWS-ReadThread] INFO net.dv8tion.jda.internal.requests.WebSocketClient - Connected to WebSocket
02:01:32.281 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.requests.WebSocketClient - Connected with gateway intents: 1100001011
02:01:32.281 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.requests.WebSocketClient - Sending Identify-packet...
02:01:32.371 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.requests.WebSocketClient - Got HELLO packet (OP 10). Initializing keep-alive.
02:01:32.574 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.handle.GuildSetupController - Setting incomplete count to 1
02:01:32.574 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.handle.GuildSetupController - Starting 75 second timeout for 1 guilds
02:01:32.770 [JDA MainWS-ReadThread] INFO net.dv8tion.jda.api.JDA - Finished Loading!
02:01:32.805 [JDA MainWS-ReadThread] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 2
02:01:32.893 [JDA MainWS-ReadThread] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
02:01:32.893 [JDA MainWS-ReadThread] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
02:01:32.904 [JDA MainWS-ReadThread] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
02:01:32.904 [JDA MainWS-ReadThread] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
02:01:32.921 [JDA MainWS-ReadThread] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
02:01:32.932 [JDA MainWS-ReadThread] INFO wowchat.realm.RealmConnector - Connecting to realm server logon.warmane.com:3724
02:01:33.001 [JDA MainWS-ReadThread] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 9661 (auto-detected)
02:01:33.004 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
02:01:33.004 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
02:01:33.009 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtilInitializations - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
02:01:33.010 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
02:01:33.011 [JDA MainWS-ReadThread] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 00:16:3e:ff:fe:06:52:b0 (auto-detected)
02:01:33.030 [JDA MainWS-ReadThread] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
02:01:33.031 [JDA MainWS-ReadThread] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
02:01:33.071 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 2
02:01:33.071 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 2
02:01:33.071 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
02:01:33.071 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
02:01:33.071 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
02:01:33.071 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
02:01:33.072 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
02:01:33.072 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
02:01:33.072 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
02:01:33.072 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
02:01:33.072 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
02:01:33.072 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
02:01:33.086 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
02:01:33.086 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
02:01:33.086 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
02:01:33.114 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.handle.GuildSetupController - Finished setup for guild 966078485846167562 firing cached events 0
02:02:00.750 [JDA RateLimit-Worker 1] DEBUG net.dv8tion.jda.internal.requests.RateLimiter - Removed 2 expired buckets
02:04:54.310 [nioEventLoopGroup-2-1] INFO wowchat.realm.RealmPacketHandlerTBC - Connected! Sending account login information...
02:04:54.320 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
02:04:54.321 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
02:04:54.321 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
02:04:54.321 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
02:04:54.334 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
02:04:54.334 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
02:04:54.335 [nioEventLoopGroup-2-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@37232b9c
02:04:54.358 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0000 - 08 27 00 57 6F 57 00 03 03 05 34 30 36 38 78 00 58 53 4F 00 53 55 6E 65 00 00 00 00 7F 00 00 01 09 52 45 4E 44 50 4F 57 45 52
02:04:54.467 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0000 - 00 00 87 02 F9 E7 90 D4 BF 70 2D 91 16 F3 05 B4 63 D9 5E E3 81 0E CA 5D 05 1C 63 AD 9F AD 20 19 2F 77 01 07 20 B7 9B 3E 2A 87 82 3C AB 8F 5E BF BF 8E B1 01 08 53 50 06 29 8B 5B AD BD 5B 53 E1 89 5E 64 4B 89 43 BF 2E B5 07 AB 4A 57 E0 D4 AE 07 7D 6E 8E C8 FC 46 0E 58 7C 4D C6 E9 60 E5 9E BB B5 CE E1 A3 BA A3 1E 99 A0 0B 21 57 FC 37 3F B3 69 CD D2 F1 00
02:04:54.521 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0001 - E3 C3 BA 36 AD F6 C1 2F C5 21 93 69 E1 B8 1A 98 B1 A2 C8 EE E7 48 D7 3F 8B 1B 56 3E 44 EE 8B 75 AC C5 19 47 E9 C1 21 9C A5 C7 4B BC D5 EC 89 E0 60 B4 59 C8 76 B4 42 46 93 08 5F B9 50 16 AA 2D C3 55 D4 7E 52 01 07 48 00 00
02:04:54.564 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0001 - 09
02:04:54.564 [nioEventLoopGroup-2-1] ERROR wowchat.realm.RealmPacketHandlerTBC - Invalid game version for this server!`

**Comment by fjaros** [comment]
@dusancvetanovic i can connect fine with platform=Mac . can you wait a little bit between connections? if you use platform=Windows , you will be disconnected due to warden.

**Comment by dusancvetanovic** [comment]
@fjaros Still no luck with platform=Mac and you say that it works for you on Warmane 3.3.5
Why is this wowchat.realm.RealmPacketHandlerTBC - TBC and not WOTLK ?
**version=3.3.5
realmlist=logon.warmane.com
realm=Frostmourne**
 
 08:07:56.813 [nioEventLoopGroup-2-1] INFO wowchat.realm.RealmPacketHandlerTBC - Connected! Sending account login information...
08:07:56.832 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
08:07:56.832 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
08:07:56.832 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
08:07:56.832 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
08:07:56.846 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
08:07:56.846 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
08:07:56.847 [nioEventLoopGroup-2-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@f1956b2
08:07:56.871 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0000 - 08 27 00 57 6F 57 00 03 03 05 34 30 36 38 78 00 58 53 4F 00 53 55 6E 65 00 00 00 00 7F 00 00 01 09 52 45 4E 44 50 4F 57 45 52
08:07:56.960 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0000 - 00 00 AB 5E B9 A5 ED E9 8C 25 51 24 F5 D8 AE 70 B1 A0 F9 23 AA 4E 56 70 15 F9 6F DF 65 77 84 D1 EA 35 01 07 20 B7 9B 3E 2A 87 82 3C AB 8F 5E BF BF 8E B1 01 08 53 50 06 29 8B 5B AD BD 5B 53 E1 89 5E 64 4B 89 43 BF 2E B5 07 AB 4A 57 E0 D4 AE 07 7D 6E 8E C8 FC 46 0E 58 7C 4D C6 E9 60 E5 9E BB B5 CE E1 A3 BA A3 1E 99 A0 0B 21 57 FC 37 3F B3 69 CD D2 F1 00
08:07:56.999 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0001 - 64 54 CF 39 9A 14 F5 50 BF CA D4 E6 A0 93 B2 5A 99 FC AF 7E 3B 2F 01 21 9A 05 86 BC 64 23 DD 85 66 B2 5B B5 B1 C0 DB 11 96 C9 DA C8 31 EF 05 DF 2E 1E 0D 34 84 DA 3F 62 13 3A DC FE 44 15 18 76 25 7C E6 32 65 B2 B8 1C 00 00
08:07:57.031 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0001 - 09
08:07:57.031 [nioEventLoopGroup-2-1] ERROR wowchat.realm.RealmPacketHandlerTBC - Invalid game version for this server!

**Comment by fjaros** [comment]
The protocol for realm (auth) server is the same for TBC and WotLK. RealmPacketHandlerTBC is correct.

I can connect to Frostmourne realm with platform=Mac on my account. There was an issue in the past with "Invalid game version for this server" being returned for Mac logins for Warmane realms, however it was fixed by commit https://github.com/fjaros/wowchat/commit/490b79d625b51ce785970e38bb46d7d8eb368b71 by computing the proper build hash for the logon proof packet.

Are you quite sure you are compiling the latest version? Look at line 167 in RealmPacketHandler.scala file. Maybe debug the bytes it fetches from the buildCrcHashes map.
If you are unsure that you compiled properly, download the release zip file.

**Comment by dusancvetanovic** [comment]
@fjaros I downloaded the latest release, this is the checksum of the file I have `dd4ee54b8c6531842e5200992805a519  wowchat.jar`
Does it match yours?
```
java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)
```
I think that on mac it gets stuck when trying to connect to the realm server. The second `RECV REALM PACKET: 0001 - 09` is way too short.
```
16:46:27.350 [nioEventLoopGroup-2-1] INFO wowchat.realm.RealmPacketHandlerTBC - Connected! Sending account login information...
16:46:27.354 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
16:46:27.355 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
16:46:27.355 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
16:46:27.355 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
16:46:27.386 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
16:46:27.386 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
16:46:27.388 [nioEventLoopGroup-2-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@30dc5995
16:46:27.412 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0000 - 08 27 00 57 6F 57 00 03 03 05 34 30 36 38 78 00 58 53 4F 00 53 55 6E 65 00 00 00 00 7F 00 00 01 09 52 45 4E 44 50 4F 57 45 52
16:46:27.502 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0000 - 00 00 A6 6F 23 DD 07 E1 80 0F 6B 7F 91 69 99 5D 6B 04 19 E7 98 3C AF AC 9D 23 4A 66 AE 0C E7 D7 0B 43 01 07 20 B7 9B 3E 2A 87 82 3C AB 8F 5E BF BF 8E B1 01 08 53 50 06 29 8B 5B AD BD 5B 53 E1 89 5E 64 4B 89 43 BF 2E B5 07 AB 4A 57 E0 D4 AE 07 7D 6E 8E C8 FC 46 0E 58 7C 4D C6 E9 60 E5 9E BB B5 CE E1 A3 BA A3 1E 99 A0 0B 21 57 FC 37 3F B3 69 CD D2 F1 00
16:46:27.540 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0001 - 68 AF A6 7E 11 87 7C 16 C8 2A B9 14 1F 38 18 A4 7E 90 9A 8C 05 DE AD 64 44 37 45 C5 8D 3E E1 38 74 75 62 48 99 E0 A1 DB 1F 17 D2 CE 50 8C C8 23 43 38 FA D9 FA E2 BD 11 42 09 77 DF DD 8C 0F D4 F1 BA CA 52 13 3B 09 F4 00 00
16:46:27.578 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0001 - 09
16:46:27.578 [nioEventLoopGroup-2-1] ERROR wowchat.realm.RealmPacketHandlerTBC - Invalid game version for this server!
```

Windows for comparison gets a full length of the second RECV REALM PACKET
```
16:44:46.581 [nioEventLoopGroup-2-1] INFO wowchat.realm.RealmPacketHandlerTBC - Connected! Sending account login information...
16:44:46.586 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
16:44:46.586 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
16:44:46.586 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
16:44:46.586 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
16:44:46.611 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
16:44:46.611 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
16:44:46.612 [nioEventLoopGroup-2-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@6b472d05
16:44:46.641 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0000 - 08 27 00 57 6F 57 00 03 03 05 34 30 36 38 78 00 6E 69 57 00 53 55 6E 65 00 00 00 00 7F 00 00 01 09 52 45 4E 44 50 4F 57 45 52
16:44:46.763 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0000 - 00 00 81 40 FF 42 7B 3C 38 CC 5A A9 A5 88 59 11 A8 92 20 35 26 01 2A 27 FB B8 22 F7 CF AF 34 3A CA 34 01 07 20 B7 9B 3E 2A 87 82 3C AB 8F 5E BF BF 8E B1 01 08 53 50 06 29 8B 5B AD BD 5B 53 E1 89 5E 64 4B 89 43 BF 2E B5 07 AB 4A 57 E0 D4 AE 07 7D 6E 8E C8 FC 46 0E 58 7C 4D C6 E9 60 E5 9E BB B5 CE E1 A3 BA A3 1E 99 A0 0B 21 57 FC 37 3F B3 69 CD D2 F1 00
16:44:46.815 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0001 - C9 9E 6B 35 5D 0D FA 58 CD 70 A7 54 F9 F7 60 30 2E 82 83 7A 4A F2 21 F5 F8 A6 DB FA FC 8E 63 27 E9 B7 C0 D1 B4 6A 8A E4 3B 4F 56 30 65 2E D2 38 7B 73 14 2B 12 22 D7 CE 65 0C F6 5A 67 5A FC C9 F4 5C 14 88 4B 1C 00 CC 00 00
16:44:46.867 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0001 - 00 35 A4 0E 85 EA 14 EB D2 B6 93 DC 1A 35 39 6F F4 94 02 DC D4 00 00 80 00 00 00 00 00 00 00
16:44:46.868 [nioEventLoopGroup-2-1] INFO wowchat.realm.RealmPacketHandlerTBC - Successfully logged into realm server. Looking for realm Frostmourne
16:44:46.868 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0010 - 00 00 00 00
16:44:46.933 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0010 - 00 00 00 00 04 00 01 00 00 42 6C 61 63 6B 72 6F 63 6B 20 5B 50 76 50 20 6F 6E 6C 79 5D 00 35 31 2E 31 37 38 2E 36 34 2E 39 37 3A 38 30 39 35 00 00 00 00 00 00 08 0A 00 00 20 46 72 6F 73 74 6D 6F 75 72 6E 65 00 35 31 2E 31 37 38 2E 36 34 2E 38 37 3A 38 30 39 36 00 00 00 40 40 02 08 0D 01 00 00 49 63 65 63 72 6F 77 6E 00 35 31 2E 39 31 2E 31 30 36 2E 31 34 38 3A 38 30 39 32 00 00 00 40 40 00 08 07 01 00 00 4C 6F 72 64 61 65 72 6F 6E 00 35 31 2E 31 37 38 2E 36 34 2E 39 37 3A 38 30 39 31 00 00 00 00 40 00 08 06 10 00
16:44:46.983 [nioEventLoopGroup-2-1] INFO wowchat.game.GameConnector - Connecting to game server Frostmourne (51.178.64.87:8096)
16:44:47.158 [nioEventLoopGroup-2-2] INFO wowchat.game.GamePacketHandlerWotLK - Connected! Authenticating...
16:44:47.185 [nioEventLoopGroup-2-2] DEBUG wowchat.game.GamePacketDecoderWotLK - RECV PACKET: 01EC - 01 00 00 00 3F 11 D7 CC 6F 03 AD 21 47 E7 A8 1A 8E 77 B3 38 0A E6 6C 97 9B 42 E2 5B 1D F8 EB A9 6B 05 20 D8 FA 67 AF C6
16:44:47.252 [nioEventLoopGroup-2-2] DEBUG wowchat.game.GamePacketEncoder - SEND PACKET: 01ED - 00 00 34 30 00 00 00 00 00 00 52 45 4E 44 50 4F 57 45 52 00 00 00 00 00 F3 52 9E 95 00 00 00 00 00 00 00 00 0D 00 00 00 03 00 00 00 00 00 00 00 50 C6 D3 43 6C 02 F8 89 E9 CE 76 1D 4D 2F 0E 3C B0 98 33 0F 9E 02 00 00 78 9C 75 D2 C1 6A C3 30 0C C6 71 EF 29 76 E9 9B EC B4 B4 50 C2 EA CB E2 9E 8B 62 7F 4B 44 6C 39 38 4E B7 F6 3D FA BE 65 B7 0D 94 F3 4F 48 F0 47 AF C6 98 26 F2 FD 4E 25 5C DE FD C8 B8 22 41 EA B9 35 2F E9 7B 77 32 FF BC 40 48 97 D5 57 CE A2 5A 43 A5 47 59 C6 3C 6F 70 AD 11 5F 8C 18 2C 0B 27 9A B5 21 96 C0 32 A8 0B F6 14 21 81 8A 46 39 F5 54 4F 79 D8 34 87 9F AA E0 01 FD 3A B8 9C E3 A2 E0 D1 EE 47 D2 0B 1D 6D B7 96 2B 6E 3A C6 DB 3C EA B2 72 0C 0D C9 A4 6A 2B CB 0C AF 1F 6C 2B 52 97 FD 84 BA 95 C7 92 2F 59 95 4F E2 A0 82 FB 2D AA DF 73 9C 60 49 68 80 D6 DB E5 09 FA 13 B8 42 01 DD C4 31 6E 31 0B CA 5F 7B 7B 1C 3E 9E E1 93 C8 8D
16:44:47.334 [nioEventLoopGroup-2-2] DEBUG wowchat.game.GamePacketDecoderWotLK - RECV PACKET: 01EE - 1B 00 00 00 00 00 00 00 00 00 02 D6 00 00 00 00
16:44:47.335 [nioEventLoopGroup-2-2] INFO wowchat.game.GamePacketHandlerWotLK - Queue enabled. Position: 214
```

**Comment by fjaros** [comment]
Using the same checksum jar, the login for platform=Mac works.
"09" in the RECV REALM PACKET just means that the server rejected your login due to invalid game version (as the bot says). The longer version with "00" in the first spot means your login was successful.

At this point I have no idea how to help you since I can't reproduce the issue. I even downloaded the same JRE:
```
wowchat>openjdk-8u322-b06-jre\bin\java.exe -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)

wowchat>openjdk-8u322-b06-jre\bin\java.exe -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dlogback.configurationFile=logback.xml -jar wowchat.jar test.conf
09:06:04.155 INFO  wowchat.WoWChat$ - Running WoWChat - v1.3.8
09:06:06.630 INFO  wowchat.WoWChat$ - Connecting to Discord...
09:06:07.377 INFO  n.d.jda.api.JDA - Login Successful!
09:06:07.566 INFO  n.d.j.i.r.WebSocketClient - Connected to WebSocket
09:06:07.775 INFO  n.d.jda.api.JDA - Finished Loading!
09:06:07.827 INFO  w.r.RealmConnector - Connecting to realm server logon.warmane.com:3724
09:06:08.630 INFO  w.r.RealmPacketHandlerTBC - Connected! Sending account login information...
09:06:08.649 DEBUG w.r.RealmPacketEncoder - SEND REALM PACKET: 0000 - 08 28 00 57 6F 57 00 03 03 05 34 30 36 38 78 00 58 53 4F 00 53 55 6E 65 00 00 00 00 7F 00 00 01 0A 42 49 47 42 41 44 42 4F 41 54
09:06:08.844 DEBUG w.r.RealmPacketDecoder - RECV REALM PACKET: 0000 - 00 00 DE 59 94 D8 D1 3F EF 6F C8 14 3C 89 AB DC B7 68 07 5E B1 6B D9 C7 5C FE AA 68 03 FC 8A A8 B9 18 01 07 20 B7 9B 3E 2A 87 82 3C AB 8F 5E BF BF 8E B1 01 08 53 50 06 29 8B 5B AD BD 5B 53 E1 89 5E 64 4B 89 A3 10 7D 21 13 6F 1C 05 27 11 F3 40 7A 95 82 CD BA 74 4E 34 3A 67 77 AA F5 A0 CE 2F BF 3E 50 97 BA A3 1E 99 A0 0B 21 57 FC 37 3F B3 69 CD D2 F1 00
09:06:08.854 DEBUG w.r.RealmPacketEncoder - SEND REALM PACKET: 0001 - 12 F8 71 41 AB CA 6A 76 88 9C 3B E8 6E 0C C7 A9 D1 55 8E CA A5 4E 14 16 01 47 F2 69 83 08 13 76 6A C9 14 EF 57 C3 7B 83 57 33 DF 35 BA D5 9E F1 A8 14 95 AF 2E CB BF 86 E6 A6 6B 35 C6 FC 75 7D A7 E9 71 2B 02 9E BB EA 00 00
09:06:09.014 DEBUG w.r.RealmPacketDecoder - RECV REALM PACKET: 0001 - 00 CD 02 96 38 71 CF 79 47 80 9C A8 93 87 72 D4 57 00 E7 2B 08 00 00 80 00 00 00 00 00 00 00
09:06:09.014 INFO  w.r.RealmPacketHandlerTBC - Successfully logged into realm server. Looking for realm Frostmourne
09:06:09.015 DEBUG w.r.RealmPacketEncoder - SEND REALM PACKET: 0010 - 00 00 00 00
09:06:09.186 DEBUG w.r.RealmPacketDecoder - RECV REALM PACKET: 0010 - 00 00 00 00 04 00 01 00 00 42 6C 61 63 6B 72 6F 63 6B 20 5B 50 76 50 20 6F 6E 6C 79 5D 00 35 31 2E 31 37 38 2E 36 34 2E 39 37 3A 38 30 39 35 00 00 00 00 00 01 08 0A 00 00 20 46 72 6F 73 74 6D 6F 75 72 6E 65 00 35 31 2E 31 37 38 2E 36 34 2E 38 37 3A 38 30 39 36 00 00 00 40 40 01 08 0D 01 00 00 49 63 65 63 72 6F 77 6E 00 35 31 2E 39 31 2E 31 30 36 2E 31 34 38 3A 38 30 39 32 00 00 00 40 40 00 08 07 01 00 00 4C 6F 72 64 61 65 72 6F 6E 00 35 31 2E 31 37 38 2E 36 34 2E 39 37 3A 38 30 39 31 00 00 00 00 40 00 08 06 10 00
09:06:09.195 INFO  w.g.GameConnector - Connecting to game server Frostmourne (51.178.64.87:8096)
09:06:09.374 INFO  w.g.GamePacketHandlerWotLK - Connected! Authenticating...
09:06:09.536 DEBUG w.g.GamePacketDecoderWotLK - RECV PACKET: 01EC - 01 00 00 00 2C 14 53 90 37 26 1B 2E 6A 49 A5 63 1D 87 57 88 0B 97 BE D7 D3 BB DA 30 1E EC 9D FC F6 58 4C 46 4C 5C E9 F8
09:06:09.546 DEBUG w.g.GamePacketEncoder - SEND PACKET: 01ED - 00 00 34 30 00 00 00 00 00 00 42 49 47 42 41 44 42 4F 41 54 00 00 00 00 00 4B 8A 31 E9 00 00 00 00 00 00 00 00 0D 00 00 00 03 00 00 00 00 00 00 00 B1 F5 B0 24 AB 28 43 E4 FA BC FF E0 47 0C BE A1 25 30 C3 17 9E 02 00 00 78 9C 75 D2 C1 6A C3 30 0C C6 71 EF 29 76 E9 9B EC B4 B4 50 C2 EA CB E2 9E 8B 62 7F 4B 44 6C 39 38 4E B7 F6 3D FA BE 65 B7 0D 94 F3 4F 48 F0 47 AF C6 98 26 F2 FD 4E 25 5C DE FD C8 B8 22 41 EA B9 35 2F E9 7B 77 32 FF BC 40 48 97 D5 57 CE A2 5A 43 A5 47 59 C6 3C 6F 70 AD 11 5F 8C 18 2C 0B 27 9A B5 21 96 C0 32 A8 0B F6 14 21 81 8A 46 39 F5 54 4F 79 D8 34 87 9F AA E0 01 FD 3A B8 9C E3 A2 E0 D1 EE 47 D2 0B 1D 6D B7 96 2B 6E 3A C6 DB 3C EA B2 72 0C 0D C9 A4 6A 2B CB 0C AF 1F 6C 2B 52 97 FD 84 BA 95 C7 92 2F 59 95 4F E2 A0 82 FB 2D AA DF 73 9C 60 49 68 80 D6 DB E5 09 FA 13 B8 42 01 DD C4 31 6E 31 0B CA 5F 7B 7B 1C 3E 9E E1 93 C8 8D
09:06:09.755 DEBUG w.g.GamePacketDecoderWotLK - RECV PACKET: 01EE - 0C 00 00 00 00 00 00 00 00 00 02
09:06:09.756 INFO  w.g.GamePacketHandlerWotLK - Successfully logged in!
09:06:09.757 DEBUG w.g.GamePacketEncoder - SEND PACKET: 0037 -
09:06:09.760 DEBUG w.g.GamePacketDecoderWotLK - RECV PACKET: 02EF - 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 02 01 00 00 00 00 00 00 00 00 00 00
09:06:09.761 DEBUG w.g.GamePacketDecoderWotLK - RECV PACKET: 04AB - 00 01 00 00
09:06:09.761 DEBUG w.g.GamePacketDecoderWotLK - RECV PACKET: 00FD - 07 00 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
09:06:09.762 DEBUG w.g.GamePacketDecoderWotLK - RECV PACKET: 02E6 - 6F B2 3D 6D E9 A5 50 50 03 F3 77 60 58 1F 04 34 32 11 B8 68 DE 53 E8 03 1A 2D 25 70 BB 82 59 8A 40 68 6D 9F 75
09:06:09.763 INFO  w.g.GamePacketHandlerWotLK - Warden handling initialized!
09:06:09.765 DEBUG w.g.GamePacketEncoder - SEND PACKET: 02E7 - 8F
09:06:09.984 DEBUG w.g.GamePacketDecoderWotLK - RECV PACKET: 02E6 - 46 B9 57 B4 19 57 D8 78 44 F9 D8 9B AB F7 A7 62 D2
09:06:09.986 DEBUG w.g.GamePacketEncoder - SEND PACKET: 02E7 - 2E 19 BB 98 D6 6B 60 D5 7C 74 57 A0 A4 FD 70 85 2F 35 CB 13 70
...
```
If you want, you can try emailing me your wowchat.conf so I can try to login with your account. I can't see why that would make a difference for invalid game version error but I don't have any other clue.

**Comment by Shulishin** [comment]
@dusancvetanovic Hey did you ever get this solved? I am currently trying to setup my own chatbot on the same server but also get the same message for invalid game version. I redownloaded the latest version, 1.3.8, as mine was 1.3.6 so I figured I'd try the update as a fresh copy to no success.

**Comment by dusancvetanovic** [comment]
@Shulishin It didn't work on my newly created account. I used VPN when I created the account on Warmane so maybe that kinda messed it up (I'm running the bot in cloud hence the different IP). After not logging in for 2-3 days the bot simply started to work and now I have him online for 2 days straight.

**Comment by Shulishin** [comment]
Ok interesting. I'll leave it for a few days and see how I go thank you. I created the account yesterday and today could not log in outside of using Windows Warden (which of course disconnects). I could log in myself as normal but tried running the bot both locally on the same machine as well as on the cloud service I utilise but had no success with either.

**Comment by mzelenka** [comment]
@Shulishin did it work? I think its Warmane issue. Tested it with two new accounts (same ip). Got the same error as you two. Then i tested it with my alt account (with 1 lvl 80 on it, so it has 4 months atleast) and bot connected (it worked).

Dont know whats the issue, but issue is there (probably on warmane side).

**Comment by fjaros** [comment]
It's definitely some logic on warmane side. It's very tough for us to guess what it could be since we don't have access to their source code. And warmane don't allow this tool on their servers so they won't be willing to work with us to figure it out.
Sorry guys, it sounds like you just need to get lucky when you connect.

**Comment by Shulishin** [comment]
@mzelenka I managed to log in for a couple days, but after one too many restarts where it would sit waiting for me to restart the entire bot (another Warmane only thing, bot would reconnect itself on Atlantiss realm), the bot was back to stating it was an invalid game version. This is definitely a Warmane thing. The first time I managed to connect after waiting the 2 days, but it was only a couple days later that it went back to being unable to connect. I have since been unable to reconnect the bot, which was over a week ago, so I have given up.
Maybe I can convince my guild mates pick a better server...

**Comment by brandonsturgeon** [comment]
> It's definitely some logic on warmane side. It's very tough for us to guess what it could be since we don't have access to their source code. And warmane don't allow this tool on their servers so they won't be willing to work with us to figure it out. Sorry guys, it sounds like you just need to get lucky when you connect.

Hi, just to clarify, this **sometimes** works on Warmane? Or it never works?

If the account has Premium on Warmane, it'll skip the queue, would that fix the issue?

**Comment by fjaros** [comment]
There are 2 issues here - Error code 1B (queue in effect) this has been fixed and is no longer an issue.
Error code 09 (Invalid game version). As posted above, it seems to work most often for accounts that were created some time ago (see mzelenka's reply). Unfortunately this is not related to queue, and we do not know why this happens for some accounts and not for others.

**Comment by brandonsturgeon** [comment]
So it's sort of luck-of-the-draw? If it works, it works?

Warmane distributes/distributed a lot of different versions of the client. Maybe that could be the reason?
I'll give this a shot later with a fresh copy of their client and let you know how it goes.
